/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package queueassignment;

import SubmitQuestions.QuestionHandler;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author Athinodwros
 */
public class MainQuiz extends javax.swing.JFrame {

    /**
     * Creates new form MainQuiz
     */
    public static int inc = 0;//inc is the variable tha helps got through out all the questions
    public static int score = 0;//if aswer is correct score++

    public MainQuiz() {
        initComponents();
        FileHandler fh = new FileHandler();// new instance of the file handler to read the questions
        ArrayList<String> la = fh.readQuestions();//I pass the Qs to an arraylist
        BreakListDown.create2DArray(la);// I break the list in 2D String array ;) 

        jLabel2.setText(BreakListDown.list[0][0]);
        jButtonA.setText(BreakListDown.list[0][1]);
        jButtonB.setText(BreakListDown.list[0][2]);
        jButtonC.setText(BreakListDown.list[0][3]);
        jButtonD.setText(BreakListDown.list[0][4]);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jButtonA = new javax.swing.JButton();
        jButtonB = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonD = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 51));
        setForeground(new java.awt.Color(255, 255, 51));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(20, 10, 460, 70);

        jButtonA.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jButtonA.setToolTipText("");
        jButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButtonA);
        jButtonA.setBounds(10, 380, 230, 50);

        jButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButtonB);
        jButtonB.setBounds(10, 440, 230, 50);

        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButtonC);
        jButtonC.setBounds(260, 380, 230, 50);

        jButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButtonD);
        jButtonD.setBounds(260, 440, 230, 50);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/park.png"))); // NOI18N
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        // TODO add your handling code here:
        if (BreakListDown.list[inc][5].equalsIgnoreCase("c")) {
            score++;
            JOptionPane.showMessageDialog(rootPane, "You Found It!!!");
        } else if (!BreakListDown.list[inc][5].equalsIgnoreCase("c")) {
            if (BreakListDown.list[inc][5].equalsIgnoreCase("b")) {
            JOptionPane.showMessageDialog(rootPane, "No the correct answer was: " + BreakListDown.list[inc][2]);
            }
            if (BreakListDown.list[inc][5].equalsIgnoreCase("a")) {
            JOptionPane.showMessageDialog(rootPane, "No the correct answer was: " + BreakListDown.list[inc][1]);
            }
            if (BreakListDown.list[inc][5].equalsIgnoreCase("d")) {
            JOptionPane.showMessageDialog(rootPane, "No the correct answer was: " + BreakListDown.list[inc][4]);
            }
        }
        inc++;
        jLabel2.setText(BreakListDown.list[inc][0]);
        jButtonA.setText(BreakListDown.list[inc][1]);
        jButtonB.setText(BreakListDown.list[inc][2]);
        jButtonC.setText(BreakListDown.list[inc][3]);
        jButtonD.setText(BreakListDown.list[inc][4]);
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAActionPerformed
        if (BreakListDown.list[inc][5].equalsIgnoreCase("a")) {
            score++;
            JOptionPane.showMessageDialog(rootPane, "You Found It!!!");
        } else if (!BreakListDown.list[inc][5].equalsIgnoreCase("a")) {
            if (BreakListDown.list[inc][5].equalsIgnoreCase("b")) {
            JOptionPane.showMessageDialog(rootPane, "No the correct answer was: " + BreakListDown.list[inc][2]);
            }
            if (BreakListDown.list[inc][5].equalsIgnoreCase("c")) {
            JOptionPane.showMessageDialog(rootPane, "No the correct answer was: " + BreakListDown.list[inc][3]);
            }
            if (BreakListDown.list[inc][5].equalsIgnoreCase("d")) {
            JOptionPane.showMessageDialog(rootPane, "No the correct answer was: " + BreakListDown.list[inc][4]);
            }

        }
        inc++;
        jLabel2.setText(BreakListDown.list[inc][0]);
        jButtonA.setText(BreakListDown.list[inc][1]);
        jButtonB.setText(BreakListDown.list[inc][2]);
        jButtonC.setText(BreakListDown.list[inc][3]);
        jButtonD.setText(BreakListDown.list[inc][4]);
    }//GEN-LAST:event_jButtonAActionPerformed

    private void jButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBActionPerformed
        // TODO add your handling code here:
        if (BreakListDown.list[inc][5].equalsIgnoreCase("b")) {
            score++;
            JOptionPane.showMessageDialog(rootPane, "You Found It!!!");
        } else if (!BreakListDown.list[inc][5].equalsIgnoreCase("b")) {
            if (BreakListDown.list[inc][5].equalsIgnoreCase("a")) {
            JOptionPane.showMessageDialog(rootPane, "No the correct answer was: " + BreakListDown.list[inc][1]);
            }
            if (BreakListDown.list[inc][5].equalsIgnoreCase("c")) {
            JOptionPane.showMessageDialog(rootPane, "No the correct answer was: " + BreakListDown.list[inc][3]);
            }
            if (BreakListDown.list[inc][5].equalsIgnoreCase("d")) {
            JOptionPane.showMessageDialog(rootPane, "No the correct answer was: " + BreakListDown.list[inc][4]);
            }
        }
        inc++;
        jLabel2.setText(BreakListDown.list[inc][0]);
        jButtonA.setText(BreakListDown.list[inc][1]);
        jButtonB.setText(BreakListDown.list[inc][2]);
        jButtonC.setText(BreakListDown.list[inc][3]);
        jButtonD.setText(BreakListDown.list[inc][4]);
    }//GEN-LAST:event_jButtonBActionPerformed

    private void jButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDActionPerformed
        // TODO add your handling code here:
        if (BreakListDown.list[inc][5].equalsIgnoreCase("d")) {
            score++;
            JOptionPane.showMessageDialog(rootPane, "You Found It!!!");
        } else if (!BreakListDown.list[inc][5].equalsIgnoreCase("d")) {
            if (BreakListDown.list[inc][5].equalsIgnoreCase("b")) {
            JOptionPane.showMessageDialog(rootPane, "No the correct answer was: " + BreakListDown.list[inc][2]);
            }
            if (BreakListDown.list[inc][5].equalsIgnoreCase("c")) {
            JOptionPane.showMessageDialog(rootPane, "No the correct answer was: " + BreakListDown.list[inc][3]);
            }
            if (BreakListDown.list[inc][5].equalsIgnoreCase("a")) {
            JOptionPane.showMessageDialog(rootPane, "No the correct answer was: " + BreakListDown.list[inc][1]);
            }
        }
        inc++;
        jLabel2.setText(BreakListDown.list[inc][0]);
        jButtonA.setText(BreakListDown.list[inc][1]);
        jButtonB.setText(BreakListDown.list[inc][2]);
        jButtonC.setText(BreakListDown.list[inc][3]);
        jButtonD.setText(BreakListDown.list[inc][4]);
    }//GEN-LAST:event_jButtonDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonA;
    private javax.swing.JButton jButtonB;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
