/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SubmitQuestions;

import static SubmitQuestions.QuestionHandler.q;
import static SubmitQuestions.QuestionHandler.questions;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Athinodwros
 */
public class AddQuestions extends JFrame {

    /**
     * Creates new form AddQuestions
     */
    public AddQuestions() {
        initComponents();
        jRadioButton1.setSelected(true);
        int a = QuestionHandler.qs + 1;
        jLabel10.setText(String.valueOf(a));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jTextFieldQuestion = new javax.swing.JTextField();
        jTextFieldA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFilepath = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BrowseButton = new javax.swing.JButton();
        NextButton = new javax.swing.JButton();
        jRadioButtonA = new javax.swing.JRadioButton();
        jRadioButtonB = new javax.swing.JRadioButton();
        jRadioButtonC = new javax.swing.JRadioButton();
        jRadioButtonD = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextFieldB = new javax.swing.JTextField();
        jTextFieldC = new javax.swing.JTextField();
        jTextFieldD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldQuestion.setAutoscrolls(false);

        jTextFieldA.setAutoscrolls(false);
        jTextFieldA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAActionPerformed(evt);
            }
        });

        jLabel1.setText("Question");

        jRadioButton1.setText("Text Question");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Image Question");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Video Question");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("File");

        jTextFieldFilepath.setAutoscrolls(false);
        jTextFieldFilepath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFilepathActionPerformed(evt);
            }
        });

        jLabel3.setText("Answer a:");

        jLabel4.setText("Answer b:");

        jLabel5.setText("Answer c:");

        jLabel6.setText("Answer d:");

        BrowseButton.setText("Browse");
        BrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseButtonActionPerformed(evt);
            }
        });

        NextButton.setText("Next");
        NextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextButtonMouseClicked(evt);
            }
        });
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        jRadioButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAActionPerformed(evt);
            }
        });

        jRadioButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBActionPerformed(evt);
            }
        });

        jRadioButtonC.setMaximumSize(new java.awt.Dimension(20, 20));
        jRadioButtonC.setMinimumSize(new java.awt.Dimension(20, 20));
        jRadioButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCActionPerformed(evt);
            }
        });

        jRadioButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel7.setText("Select");

        jLabel8.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel8.setText(" the  correct");

        jButton1.setText("Back");

        jButton2.setText("Discard & Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextFieldB.setAutoscrolls(false);
        jTextFieldB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBActionPerformed(evt);
            }
        });

        jTextFieldC.setAutoscrolls(false);
        jTextFieldC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCActionPerformed(evt);
            }
        });

        jTextFieldD.setAutoscrolls(false);
        jTextFieldD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel9.setText(" Answer ");

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(jTextFieldFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BrowseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66)
                .addComponent(jLabel10)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(101, 101, 101)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(jButton2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jRadioButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButton3)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextFieldD, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadioButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(31, 31, 31))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadioButtonD)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadioButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadioButtonB)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BrowseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jRadioButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)
                                            .addComponent(jRadioButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel4)
                                                .addComponent(jTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jRadioButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(jTextFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonD)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextButton)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jRadioButton3.setSelected(false);
        jRadioButton1.setSelected(false);

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextFieldFilepathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFilepathActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldFilepathActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(false);
        jRadioButton1.setSelected(false);


    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void BrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseButtonActionPerformed
        // TODO add your handling code here:
        FileOpenClass fl = new FileOpenClass();
        
        jTextFieldFilepath.setText(fl.userPicker());
    }//GEN-LAST:event_BrowseButtonActionPerformed

    private void jTextFieldAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        // check if the user endered the correct data to every field to proceed to the next question; 
        if (jRadioButton2.isSelected() || jRadioButton3.isSelected()) {
            if (jRadioButton2.isSelected()) {
                QuestionHandler.q[QuestionHandler.qs][7]= String.valueOf(2);
            }else QuestionHandler.q[QuestionHandler.qs][7]= String.valueOf(3);
            if (jTextFieldFilepath.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "You selected video or image question \n but you did not choose a file.");
            } else {
                if (!jTextFieldA.getText().equals("") && !jTextFieldB.getText().equals("") && !jTextFieldC.getText().equals("") && !jTextFieldD.getText().equals("") && !jTextFieldQuestion.getText().equals("")) {
                    if (jRadioButtonA.isSelected() || jRadioButtonB.isSelected() || jRadioButtonC.isSelected() || jRadioButtonD.isSelected()) {

                        QuestionHandler.q[QuestionHandler.qs][0] = jTextFieldQuestion.getText();
                        QuestionHandler.q[QuestionHandler.qs][1] = jTextFieldA.getText();
                        QuestionHandler.q[QuestionHandler.qs][2] = jTextFieldB.getText();
                        QuestionHandler.q[QuestionHandler.qs][3] = jTextFieldC.getText();
                        QuestionHandler.q[QuestionHandler.qs][4] = jTextFieldD.getText();
                        if (jRadioButtonA.isSelected()) {
                            QuestionHandler.q[QuestionHandler.qs][5] = "a";
                        }
                        if (jRadioButtonB.isSelected()) {
                            QuestionHandler.q[QuestionHandler.qs][5] = "b";
                        }
                        if (jRadioButtonC.isSelected()) {
                            QuestionHandler.q[QuestionHandler.qs][5] = "c";
                        }
                        if (jRadioButtonD.isSelected()) {
                            QuestionHandler.q[QuestionHandler.qs][5] = "d";
                        }
                        QuestionHandler.q[QuestionHandler.qs][6] = jTextFieldFilepath.getText();
                        String b = (q[QuestionHandler.qs][0]+","+q[QuestionHandler.qs][1]+","+q[QuestionHandler.qs][2]+","+q[QuestionHandler.qs][3]+","+q[QuestionHandler.qs][4]+","+q[QuestionHandler.qs][5]+","+q[QuestionHandler.qs][6]+","+q[QuestionHandler.qs][7]);
                        questions.add(b);

                        QuestionHandler.qs++;
                        if (QuestionHandler.qs==5) {
//                            QuestionHandler.toArrayList();
                            try {
                            QuestionHandler.saveToFile();
                            } catch (Exception e) {
                            }
                         }
                        int a = QuestionHandler.qs + 1;
                        jLabel10.setText(String.valueOf(a));
                        //after that I refresh the filds to the initial state empty.
                        jTextFieldQuestion.setText("");
                        jTextFieldA.setText("");
                        jTextFieldB.setText("");
                        jTextFieldC.setText("");
                        jTextFieldD.setText("");
                        jTextFieldFilepath.setText("");
                        jRadioButton1.setSelected(true);
                        jRadioButton2.setSelected(false);
                        jRadioButton3.setSelected(false);
                        jRadioButtonA.setSelected(false);
                        jRadioButtonB.setSelected(false);
                        jRadioButtonC.setSelected(false);
                        jRadioButtonD.setSelected(false);

                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Please selecet the correct answer and try again");
                    }
                }
            }

        } else if (jRadioButton1.isSelected()) {//if only the texquestion field is selected i do all the same but pass null to file path.
             
            if (!jTextFieldA.getText().equals("") && !jTextFieldB.getText().equals("") && !jTextFieldC.getText().equals("") && !jTextFieldD.getText().equals("") && !jTextFieldQuestion.getText().equals("")) {
                if (jRadioButtonA.isSelected() || jRadioButtonB.isSelected() || jRadioButtonC.isSelected() || jRadioButtonD.isSelected()) {

                    QuestionHandler.q[QuestionHandler.qs][0] = jTextFieldQuestion.getText();
                    QuestionHandler.q[QuestionHandler.qs][1] = jTextFieldA.getText();
                    QuestionHandler.q[QuestionHandler.qs][2] = jTextFieldB.getText();
                    QuestionHandler.q[QuestionHandler.qs][3] = jTextFieldC.getText();
                    QuestionHandler.q[QuestionHandler.qs][4] = jTextFieldD.getText();
                    if (jRadioButtonA.isSelected()) {
                        QuestionHandler.q[QuestionHandler.qs][5] = "a";
                    }
                    if (jRadioButtonB.isSelected()) {
                        QuestionHandler.q[QuestionHandler.qs][5] = "b";
                    }
                    if (jRadioButtonC.isSelected()) {
                        QuestionHandler.q[QuestionHandler.qs][5] = "c";
                    }
                    if (jRadioButtonD.isSelected()) {
                        QuestionHandler.q[QuestionHandler.qs][5] = "d";
                    }
                    QuestionHandler.q[QuestionHandler.qs][6] = "null";
                    QuestionHandler.q[QuestionHandler.qs][7]= String.valueOf(1);
                    String b = (q[QuestionHandler.qs][0]+","+q[QuestionHandler.qs][1]+","+q[QuestionHandler.qs][2]+","+q[QuestionHandler.qs][3]+","+q[QuestionHandler.qs][4]+","+q[QuestionHandler.qs][5]+","+q[QuestionHandler.qs][6]+","+q[QuestionHandler.qs][7]);
                     questions.add(b);

                    QuestionHandler.qs++;
                     if (QuestionHandler.qs==5) {
//                            QuestionHandler.toArrayList();
                            try {
                            QuestionHandler.saveToFile();
                            } catch (Exception e) {
                            }
                         }
                    int a = QuestionHandler.qs + 1;
                    jLabel10.setText(String.valueOf(a));
                    JOptionPane.showMessageDialog(rootPane, "The question is saved");
                    //after that I refresh the filds to the initial state empty.
                    jTextFieldQuestion.setText("");
                    jTextFieldA.setText("");
                    jTextFieldB.setText("");
                    jTextFieldC.setText("");
                    jTextFieldD.setText("");
                    jTextFieldFilepath.setText(null);
                    jRadioButton1.setSelected(true);
                    jRadioButton2.setSelected(false);
                    jRadioButton3.setSelected(false);
                    jRadioButtonA.setSelected(false);
                    jRadioButtonB.setSelected(false);
                    jRadioButtonC.setSelected(false);
                    jRadioButtonD.setSelected(false);
                }
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "you checked something wrong");
        }


    }//GEN-LAST:event_NextButtonActionPerformed

    private void jRadioButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAActionPerformed
        // TODO add your handling code here:

        jRadioButtonA.setSelected(true);
        jRadioButtonB.setSelected(false);
        jRadioButtonC.setSelected(false);
        jRadioButtonD.setSelected(false);

    }//GEN-LAST:event_jRadioButtonAActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        try {
            System.exit(1);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBActionPerformed

    private void jTextFieldCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCActionPerformed

    private void jTextFieldDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldDActionPerformed

    private void jRadioButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCActionPerformed
        // TODO add your handling code here:

        jRadioButtonA.setSelected(false);
        jRadioButtonB.setSelected(false);
        jRadioButtonC.setSelected(true);
        jRadioButtonD.setSelected(false);

    }//GEN-LAST:event_jRadioButtonCActionPerformed

    private void jRadioButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBActionPerformed
        // TODO add your handling code here:
        jRadioButtonA.setSelected(false);
        jRadioButtonB.setSelected(true);
        jRadioButtonC.setSelected(false);
        jRadioButtonD.setSelected(false);

    }//GEN-LAST:event_jRadioButtonBActionPerformed

    private void jRadioButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDActionPerformed
        // TODO add your handling code here:

        jRadioButtonA.setSelected(false);
        jRadioButtonB.setSelected(false);
        jRadioButtonC.setSelected(false);
        jRadioButtonD.setSelected(true);

    }//GEN-LAST:event_jRadioButtonDActionPerformed

    private void NextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextButtonMouseClicked
        // TODO add your handling code here:
        // check if the user endered the correct data to every field to proceed to the next question; 
//        if (jRadioButton2.isSelected() || jRadioButton3.isSelected()) {
//            if (jTextFieldFilepath == null) {
//                JOptionPane.showMessageDialog(rootPane, "You selected video or image question \n but you did not choose a file.");
//
//                if (jTextFieldA != null && jTextFieldB != null && jTextFieldC != null && jTextFieldD != null && jTextFieldQuestion != null) {
//                    if (jRadioButtonA.isSelected() || jRadioButtonB.isSelected() || jRadioButtonC.isSelected() || jRadioButtonD.isSelected()) {
//
//                        QuestionHandler.q[QuestionHandler.qs][0] = jTextFieldQuestion.getText();
//                        QuestionHandler.q[QuestionHandler.qs][1] = jTextFieldA.getText();
//                        QuestionHandler.q[QuestionHandler.qs][2] = jTextFieldB.getText();
//                        QuestionHandler.q[QuestionHandler.qs][3] = jTextFieldC.getText();
//                        QuestionHandler.q[QuestionHandler.qs][4] = jTextFieldD.getText();
//                        if (jRadioButtonA.isSelected()) {
//                            QuestionHandler.q[QuestionHandler.qs][5] = "a";
//                        }
//                        if (jRadioButtonB.isSelected()) {
//                            QuestionHandler.q[QuestionHandler.qs][5] = "b";
//                        }
//                        if (jRadioButtonC.isSelected()) {
//                            QuestionHandler.q[QuestionHandler.qs][5] = "c";
//                        }
//                        if (jRadioButtonD.isSelected()) {
//                            QuestionHandler.q[QuestionHandler.qs][5] = "d";
//                        }
//                        QuestionHandler.q[QuestionHandler.qs][6] = jTextFieldFilepath.getText();
//
//                        QuestionHandler.qs++;
//                        //after that I refresh the filds to the initial state empty.
//                        jTextFieldQuestion.setText("");
//                        jTextFieldA.setText("");
//                        jTextFieldB.setText("");
//                        jTextFieldC.setText("");
//                        jTextFieldD.setText("");
//                        jTextFieldFilepath.setText("");
//                        jRadioButton1.setSelected(true);
//                        jRadioButton2.setSelected(false);
//                        jRadioButton3.setSelected(false);
//                        jRadioButtonA.setSelected(false);
//                        jRadioButtonB.setSelected(false);
//                        jRadioButtonC.setSelected(false);
//                        jRadioButtonD.setSelected(false);
//
//                    } else {
//                        JOptionPane.showMessageDialog(rootPane, "Please selecet the correct answer and try again");
//                    }
//                }
//
//            }
//        } else if (jRadioButton1.isSelected()) {//if only the texquestion field is selected i do all the same but pass null to file path.
//            if (jTextFieldFilepath == null) {
//                JOptionPane.showMessageDialog(rootPane, "You selected video or image question \n but you did not choose a file.");
//
//                if (jTextFieldA != null && jTextFieldB != null && jTextFieldC != null && jTextFieldD != null && jTextFieldQuestion != null) {
//                    if (jRadioButtonA.isSelected() || jRadioButtonB.isSelected() || jRadioButtonC.isSelected() || jRadioButtonD.isSelected()) {
//
//                        QuestionHandler.q[QuestionHandler.qs][0] = jTextFieldQuestion.getText();
//                        QuestionHandler.q[QuestionHandler.qs][1] = jTextFieldA.getText();
//                        QuestionHandler.q[QuestionHandler.qs][2] = jTextFieldB.getText();
//                        QuestionHandler.q[QuestionHandler.qs][3] = jTextFieldC.getText();
//                        QuestionHandler.q[QuestionHandler.qs][4] = jTextFieldD.getText();
//                        if (jRadioButtonA.isSelected()) {
//                            QuestionHandler.q[QuestionHandler.qs][5] = "a";
//                        }
//                        if (jRadioButtonB.isSelected()) {
//                            QuestionHandler.q[QuestionHandler.qs][5] = "b";
//                        }
//                        if (jRadioButtonC.isSelected()) {
//                            QuestionHandler.q[QuestionHandler.qs][5] = "c";
//                        }
//                        if (jRadioButtonD.isSelected()) {
//                            QuestionHandler.q[QuestionHandler.qs][5] = "d";
//                        }
//                        QuestionHandler.q[QuestionHandler.qs][6] = null;
//
//                        QuestionHandler.qs++;
//                        JOptionPane.showMessageDialog(rootPane, "The question is saved");
//                        //after that I refresh the filds to the initial state empty.
//                        jTextFieldQuestion.setText("");
//                        jTextFieldA.setText("");
//                        jTextFieldB.setText("");
//                        jTextFieldC.setText("");
//                        jTextFieldD.setText("");
//                        jTextFieldFilepath.setText(null);
//                        jRadioButton1.setSelected(true);
//                        jRadioButton2.setSelected(false);
//                        jRadioButton3.setSelected(false);
//                        jRadioButtonA.setSelected(false);
//                        jRadioButtonB.setSelected(false);
//                        jRadioButtonC.setSelected(false);
//                        jRadioButtonD.setSelected(false);
//                    }
//                }
//            }
//        } else {
//            JOptionPane.showMessageDialog(rootPane, "you checked something wrong");
//        }
    }//GEN-LAST:event_NextButtonMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            
        QuestionHandler.saveToFile();
        } catch (Exception e) {
        }
        System.out.println(QuestionHandler.questions);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddQuestions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrowseButton;
    private javax.swing.JButton NextButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButtonA;
    private javax.swing.JRadioButton jRadioButtonB;
    private javax.swing.JRadioButton jRadioButtonC;
    private javax.swing.JRadioButton jRadioButtonD;
    private javax.swing.JTextField jTextFieldA;
    private javax.swing.JTextField jTextFieldB;
    private javax.swing.JTextField jTextFieldC;
    private javax.swing.JTextField jTextFieldD;
    private javax.swing.JTextField jTextFieldFilepath;
    private javax.swing.JTextField jTextFieldQuestion;
    // End of variables declaration//GEN-END:variables
}
